#!/usr/bin/python
# Created by vay3t

import I2C_LCD_driver
import time
import commands

mylcd = I2C_LCD_driver.lcd()

def show_ipwlan0():
	ip_addr=commands.getoutput("ifconfig wlan0 | awk '{print $2}' | grep 'addr:1' | cut -d ':' -f2")
	mylcd.lcd_display_string("IP Address:", 1) 
	mylcd.lcd_display_string(ip_addr, 2)

def show_date():
	mylcd.lcd_display_string("Time: %s" %time.strftime("%H:%M:%S"), 1)
	mylcd.lcd_display_string("Date: %s" %time.strftime("%m/%d/%Y"), 2)

def show_temp():
	temperature=commands.getoutput("vcgencmd measure_temp")
	mylcd.lcd_display_string(temperature,1)

def show_uptime():
	uptime=commands.getoutput("uptime | cut -d "," -f1")
	mylcd.lcd_display_string("uptime:", 1) 
	mylcd.lcd_display_string(uptime, 2)

def show_help():
	print """options:
	show_ipwlan0
	show_temp
	show_date
	show_uptime
	help
	"""

try:
	while True:
		command=raw_input("> ")
		time.sleep(1)
		mylcd.lcd_clear()

		if command=="show_ipwlan0":
			show_ipwlan0()
		elif command=="show_temp":
			show_temp()
		elif command=="show_date":
			show_date()
		elif command=="show_uptime":
			show_uptime()
		elif command=="help":
			show_help()
		else:
			mylcd.lcd_display_string("Command no exist",1)

except KeyboardInterrupt:
	mylcd.lcd_clear()
	mylcd.lcd_display_string("quit", 1)
	time.sleep(3)
	mylcd.lcd_clear()
	exit()
