#!/bin/bash

BLACK='\e[30m'
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'
PURPLE='\e[35m'
CYAN='\e[36m'
WHITE='\e[37m'
NC='\e[0m'

if [ `lsb_release -i | awk '{print $3}'` != Raspbian ]; then
	echo -e "\n${RED}[*] Your distro is not supported\n${NC}"
	exit 1
fi

echo -e "${CYAN}               _                 ___             _              "
echo "              | |__   __ ___  __/ _ \ _ __ _ __ (_)             "
echo "              | '_ \ / _' \ \/ / | | | '__| '_ \| |             "
echo "              | | | | (_| |>  <| |_| | |  | |_) | |             "
echo '              |_| |_|\__,_/_/\_\\___/|_|  | .__/|_|             '
echo "                                          |_|                   "
echo -e "${NC}"
echo -e "${RED}                  === hax0rpi Release 1.1 ===                   ${NC}"
echo -e "${RED}                   codename: Maromota Dorada                   ${NC}"
echo -e "${YELLOW}           A Raspberry Pi Hacker Tools suite by Vay3t           ${NC}"
echo ""
echo "----------------------------------------------------------------"
echo -e "${GREEN}    This installer will load a comprehensive of hacker tools    "
echo "      suite onto your Raspberry Pi. Note that the Raspbian      "
echo "     distribution must be installed onto the SD card before     "
echo -e "     proceeding. See README (if exist) for more information.    ${NC}"
echo ""
echo -e "${CYAN}[>] Press ENTER to continue, CTRL+C to abort.${NC}"
read INPUT
echo ""

# change password
#passwd pi

echo -e "${YELLOW}[!] enable ssh${NC}"
sudo update-rc.d ssh enable

# secret directory
secret=arsenal
cd
mkdir $secret && cd $secret
echo -e "\n${YELLOW}[+] folder 'secret' created${NC}"

# update system
echo -e "\n${YELLOW}[!] update and upgrade system${NC}"
sudo apt-get update
sudo apt-get dist-upgrade -y

# install from apt-get
echo -e "\n${YELLOW}\n[!] install tools with apt-get${NC}"
sudo apt-get install -y \
	apache2 \
	arp-scan \
	crunch \
	curl \
	dhex \
	dnsmasq \
	dsniff \
	ettercap-text-only \
	gdb \
	git \
	hexedit \
	hostapd \
	hydra \
	iw \
	john \
	kismet \
	libimage-exiftool-perl \
	locate \
	macchanger \
	masscan \
	mariadb-client \
	mariadb-server \
	mycli \
	nmap \
	openvpn \
	php \
	proxychains \
	python-dev \
	python-pip \
	ruby-full \
	screen \
	smbclient \
	tcpdump \
	tmux \
	tor \
	torsocks \
	tree \
	vim \
	wipe \
	wireless-tools \
	whois;

# install from gems
echo -e "\n${YELLOW}[!] install from gems${NC}"
sudo gem install anemone wpascan bundle

# install from pip
echo -e "\n${YELLOW}[!] install from pip${NC}"
sudo pip install exrex sqlmap shodan webtech wafw00f requests beautifulsoup4

# install scapy
echo -e "\n${YELLOW}[!] install scapy${NC}"
sudo apt install -y python-scapy python-matplotlib python-pyx python-ecdsa

# clone repos
echo -e "\n${YELLOW}[!] clone repos${NC}"
git clone https://github.com/danielmiessler/SecLists
git clone https://github.com/berzerk0/Probable-Wordlists
git clone https://github.com/Mebus/cupp
git clone https://github.com/drwetter/testssl.sh
git clone https://github.com/m4ll0k/Atlas
git clone https://github.com/binkybear/rock3tman
git clone https://github.com/commixproject/commix
git clone https://github.com/maurosoria/dirsearch
git clone https://github.com/lgandx/Responder
git clone https://github.com/g0tmi1k/msfpc
wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse

# install sublist3r
echo -e "\n${YELLOW}[!] install Sublist3r${NC}"
git clone https://github.com/aboul3la/Sublist3r
cd Sublist3r
sudo pip install -r requirements.txt 
cd && cd $secret

# install whatwaf
echo -e "\n${YELLOW}[!] install WhatWaf${NC}"
git clone https://github.com/Ekultek/WhatWaf
cd WhatWaf
sudo pip install -r requirements.txt 
cd && cd $secret

# install routersploit
echo -e "\n${YELLOW}[!] install routersploit${NC}"
git clone https://github.com/threat9/routersploit
cd routersploit
sudo pip install -r requirements.txt 
cd && cd $secret

# install theharvester
echo -e "\n${YELLOW}[!] install theharvester${NC}"
git clone https://github.com/laramies/theHarvester
cd theHarvester
sudo pip install -r requirements.txt 
cd && cd $secret

# install windows-exploit-suggester
echo -e "\n${YELLOW}[!] install windows-exploit-suggester${NC}"
git clone https://github.com/GDSSecurity/Windows-Exploit-Suggester
cd Windows-Exploit-Suggester
./windows-exploit-suggester.py --update
cd && cd $secret

#install cewl
echo -e "\n${YELLOW}[!] install cewl${NC}"
git clone https://github.com/digininja/CeWL
cd CeWL
bundle install
cd && cd $secret

# install metasploit
echo -e "\n${YELLOW}[!] install metasploit${NC}"
wget https://apt.metasploit.com/pool/main/m/metasploit-framework/metasploit-framework_4.17.1%2B20180712133528.git.8.5e891c9~1rapid7-1_armhf.deb
sudo dpkg -i metasploit-framework_4.17.1+20180712133528.git.8.5e891c9~1rapid7-1_armhf.deb
rm -f metasploit-framework_4.17.1+20180712133528.git.8.5e891c9~1rapid7-1_armhf.deb
sudo msfupdate
sudo apt install postgresql
wget https://raw.githubusercontent.com/vay3t/hax0rpi/master/msfdb
chmod +x msfdb
sudo ./msfdb init
cd && cd $secret

# install golang
echo -e "\n${YELLOW}[!] install golang${NC}"
sudo apt install golang
cd && mkdir go
echo 'export GOPATH=$HOME/go' >> ~/.profile
echo 'PATH="$HOME/go/bin:$PATH"' >> ~/.profile
source ~/.profile
cd && cd $secret

# install gobuster
echo -e "\n${YELLOW}[!] install gobuster${NC}"
go get github.com/OJ/gobuster
cd && cd $secret

# install bettercap
echo -e "\n${YELLOW}[!] install bettercap${NC}"
sudo apt install libpcap-dev libnetfilter-queue-dev
wget https://github.com/bettercap/bettercap/releases/download/v2.17/bettercap_linux_arm7_2.17.zip
unzip bettercap_linux_arm7_2.17.zip
rm README.md 
rm LICENSE.md
cd && cd $secret

# install aircrack-ng
echo -e "\n${YELLOW}[!] install aircrack-ng${NC}"
sudo apt install -y autoconf automake libtool
sudo apt install -y libssl-dev libgcrypt20-dev libnl-3-dev libnl-genl-3-dev ethtool
wget https://download.aircrack-ng.org/aircrack-ng-1.5.2.tar.gz
echo "decompress aircrack-ng-1.2.tar.gz"
tar -zxvf aircrack-ng-1.5.2.tar.gz
rm aircrack-ng-1.5.2.tar.gz
cd aircrack-ng-1.5.2
./autogen
make
sudo make install
sudo airodump-ng-oui-update
cd && cd $secret

# instal mdk3
echo -e "\n${YELLOW}[!] install mdk3${NC}"
wget http://aspj.aircrack-ng.org/mdk3-v6.tar.bz2
tar jxvf mdk3-v6.tar.bz2
rm mdk3-v6.tar.bz2
cd mdk3-v6
make
sudo make install
cd && cd $secret

# install pixie-dust
echo -e "\n${YELLOW}[!] install pixie-dust${NC}"
git clone https://github.com/wiire/pixiewps
cd pixiewps*/
cd src/
make
sudo make install
cd && cd $secret

# install reaver
echo -e "\n${YELLOW}[!] install reaver${NC}"
sudo apt-get -y install build-essential libpcap-dev sqlite3 libsqlite3-dev
git clone https://github.com/t6x/reaver-wps-fork-t6x
cd reaver-wps-fork-t6x*/
cd src/
./configure
make
sudo make install
cd && cd $secret

# install shc
echo -e "\n${YELLOW}[!] install shc${NC}"
git clone https://github.com/neurobin/shc
cd shc
./configure
make
sudo make install
cd && cd $secret

# install searchsploit
sudo git clone https://github.com/offensive-security/exploitdb.git /opt/exploitdb
sed 's|path_array+=(.*)|path_array+=("/opt/exploitdb")|g' /opt/exploitdb/.searchsploit_rc > ~/.searchsploit_rc
sudo ln -sf /opt/exploitdb/searchsploit /usr/local/bin/searchsploit

# disable service
echo -e "\n${YELLOW}[!] disable services${NC}"
sudo update-rc.d apache2 disable
sudo update-rc.d bluetooth disable
sudo update-rc.d dnsmasq disable
sudo update-rc.d mariadb disable
sudo update-rc.d postgresql disable
sudo update-rc.d tor disable

# update updatedb
echo -e "\n${YELLOW}[!] updatedb${NC}"
sudo updatedb

# need reboot
echo -e "\n${GREEN}[>] Need reboot${NC}"
